/**
 * Generated by FakerAndroid for doc or help by https://github.com/Efaker/FakerAndroid
 */
package com.fakler.java.scaffoding;

import android.app.Application;

public class TestApplication extends Application {

}
