/**
 * Generated by FakerAndroid for doc or help by https://github.com/Efaker/FakerAndroid
 */
void onJniLoad(JavaVM *vm, void *reserved);

/**
 * install packed dexes
 * @param env
 * @param instance
 * @param base
 * @param fakeDexAssetFileName
 */
void fakeDex(JNIEnv *env, jobject instance,jobject base,char *fakeDexAssetFileName);

/**
 * replace application to original
 * @param env
 * @param instance
 * @param application
 * @param targetApp
 * @return
 */
void fakeApp(JNIEnv *env, jobject instance,jobject application,jboolean b);

/**
 * get base address of a .so file
 * @param soname lilke libil2cpp.so
 * @return
 */
long baseAddr(char *soname);


/**
 * Hook so method by baseAddr+offset
 * @param function_address
 * @param replace_call
 * @param origin_call
 */
void fakeCpp(void *function_address, void *replace_call,void **origin_call);


/**
 * install a stantard dex
 * @param path
 * @return
 */
bool installDex(JNIEnv* env, jobject jobject, string dexPath);


/**
 * install several of stantard dexes
 * @param path
 * @return
 */
bool installDex(JNIEnv* env, jobject jobject, vector<string>* dexPaths);


